### ISSUE TITLE
Javascript execution error into array.js

### ISSUE THREAD

**Issue by vejmarie** [edf-hpc/slurm-web#140]
The code in array.js shall be upgraded to 

define([
  'handlebars'
], function(Handlebars) {
  Handlebars.registerHelper('join', function(item, separator) {
    var args = Array.prototype.slice.call(item);    
    return args.join(separator);
  });
});

As item is not necessarly an array it is raising Javascript execution on Chrome and latest Firefox prohibiting the partitions table to be displayed

**Comment by rezib** [comment]
Hi @vejmarie,

The join function was employed because PySLURM used to send partition's nodes within an array. As explained in 3478320 commit message, it changed lately. Then, I prefer to simply remove the join method as it is not needed anymore, it was the only placed it was used in the code.

Anyway, thanks for reporting it!
