### ISSUE TITLE
RPM packages

### ISSUE THREAD

**Issue by AaronTHolt** [edf-hpc/slurm-web#51]
It is currently very difficult to get Slurm-web running on anything that isn't debian. An rpm would fix this.

**Comment by rezib** [comment]
Yes, that's right, we've focused mainly on Debian because it is our main distrib in EDF. We would be pleased to get help from people used to RPM based distribs to write a proper spec file.

Currently, slurm-web is a native Debian package. That basically means the versions of the software and the deb packages are closely tighted. Maybe we could start by turning slurm-web repository into a distrib neutral software (by removing debian/ sub-directory) and then create 2 repos:

- one for deb packaging with all Debian related specifics
- another one for RPM packaging

What do you guys think about it?

**Comment by flegoff** [comment]
I would recommend a specific subdirectory that would include the different packaging manifests (/distribs?).​


Respository fragmentation will increase the cost of maintaining packages in the mean term.

**Comment by mehdid** [comment]
I don't agree on the difficulty not on the fact that slurm-web is Debian specific. It certainly requires someone with knowledge about RPM packaging, but that's not hard per se.
Besides, there is nothing in slurm-web's code which is Debian specific. The fact that we ship a debian directory can be ignored by users or RPM-based distros.
Having two repos can be a bit heavy to manage and the subdirectory cannot be implemented (AFAIK) since packaging tools expect specific files at the top directory of the project. One could easily imagine a branch per distribution though.
For the brave souls, here is the list of files provided by each debian binary package (up to version 1.1). If you mimick that in the .spec file, you'll have working RPMs:

slurm-web-dashboard: 
/etc/apache2/conf-available/slurm-web-dashboard.conf 
/usr/share/slurm-web/dashboard/css/dashboard.css 
/usr/share/slurm-web/dashboard/static/logo.png 
/usr/share/slurm-web/dashboard/js/slurm-dashboard.js 
/usr/share/slurm-web/dashboard/index.html 

slurm-web-restapi: 
/etc/slurm-web/racks.xml 
/etc/apache2/conf-available/slurm-web-restapi.conf 
/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi 
/usr/share/slurm-web/restapi/slurmrestapi.py 
/usr/share/slurm-web/restapi/schema/dtd/racks.dtd

**Comment by datakid** [comment]
(see https://github.com/edf-hpc/slurm-web/pull/53#issuecomment-230800580 for current state of affairs)

**Comment by rezib** [comment]
Hi @AaronTHolt, 

Slurm-web v2.4.0 has just been released with a spec file to build RPM for el8. Please give it a try!

Let me know if you see any reason to re-open this issue.
